accounts/urls.py
from django.urls import path, include, re_path
from figures import views as f_views
from accounts import views as a_views
from django.contrib.auth import views as auth_views

app_name='accounts'

urlpatterns = [

    path('login/', auth_views.LoginView.as_view(template_name='accounts/a_login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', a_views.SignUpView.as_view(), name='signup'),

]

figures/urls.py
from django.urls import path, include, re_path
from figures import views

app_name='figures'

urlpatterns = [
    path(r'^tables/', views.TablesView, name='tables'),
    path(r'^create_word/', views.DictionaryCreateView.as_view(), name='create_word'),
    path(r'^update_word/(?P<pk>[-\w]+)/$', views.DictionaryUpdateView.as_view(), name='update_word'),
    path(r'^delete_word/(?P<pk>[-\w]+)/$', views.DictionaryDeleteView.as_view(), name='delete_word'),
    path(r'^create_figure/', views.FiguresCreateView.as_view(), name= 'create_figure'),
    path(r'^update_figure/(?P<pk>[-\w]+)/$', views.FiguresUpdateView.as_view(), name='update_figure'),
    path(r'^delete_figure/(?P<pk>[-\w]+)/$', views.FiguresDeleteView.as_view(), name='delete_figure'),


]

rueda/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from figures import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('accounts/', include('accounts.urls')),
    re_path('figures/', include('figures.urls')),
    path('', views.IndexView.as_view(), name='index'),

]

accounts/models.py
from django.db import models

# Create your models here.

figures/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Dictionary(models.Model):
    name= models.CharField(max_length=100, unique=True)
    description= models.TextField()
    url= models.URLField(blank=True)
    # icon= pass
    date=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('figures:tables')


class Figures(models.Model):
    name= models.CharField(max_length=100, unique=True)
    description= models.TextField()
    url= models.URLField(blank=True)
    # icon= pass
    date= models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('figures:tables')

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
# Create your views here.


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/a_signup.html'

figures/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)
from django.http import HttpResponse
from django.urls import reverse_lazy
from figures.models import Dictionary, Figures
from django.template import loader


# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'


class DictionaryCreateView(CreateView):
    fields = ('name', 'description', 'url')
    model = Dictionary
    template_name = 'figures/r_add_form.html'


class DictionaryUpdateView(UpdateView):
    fields = ('name', 'description', 'url')
    model = Dictionary
    template_name = 'figures/r_add_form.html'


class DictionaryDeleteView(DeleteView):
    model = Dictionary
    success_url = reverse_lazy('figures:tables')
    template_name = 'figures/r_delete.html'


class FiguresCreateView(CreateView):
    fields = ('name', 'description', 'url')
    model = Figures
    template_name = 'figures/r_add_form.html'


class FiguresUpdateView(UpdateView):
    fields = ('name', 'description', 'url')
    model = Figures
    template_name = 'figures/r_add_form.html'


class FiguresDeleteView(DeleteView):
    model = Figures
    success_url = reverse_lazy('figures:tables')
    template_name = 'figures/r_delete.html'


def TablesView(request):
    dictionary_table = Dictionary.objects.all()
    figures_table = Figures.objects.all()
    template = loader.get_template('figures/r_list.html')
    context = {
        'dictionary_table':dictionary_table,
        'figures_table':figures_table,
    }
    return HttpResponse(template.render(context,request))

templates/accounts/a_login.html
{%extends 'base.html'%}
{% block body_block %}

<div class="jumbotron" style="background-color:#FF4500;">
  <h2 class="pb-5">Log In:</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class='btn btn-primary'>Log In!</button>
    <h4 class="pt-5">Don't have account?</h4>
    <a class="btn btn-info btn-sm" href="{% url 'accounts:signup' %}">Sign Up</a>
  </form>

</div>

{% endblock %}

templates/accounts/a_signup.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron" style="background-color:#FF4500;">
  <h2 class="pb-5">Sign Up!</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class='btn btn-primary'>Sign Up</button>
  </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load has_group %}
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/styling.css' %}">
    <!-- Bootsrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title></title>
  </head>
  <body class="main">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'index' %}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'figures:tables' %}">Figury<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin panel<span class="sr-only">(current)</span></a>
          </li>
        </ul>
        {% else %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active"></li>
          </ul>
        {% endif %}
        <ul class="navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <span class="navbar-text">Witaj {{user.username}}</span>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout<span class="sr-only">(current)</span></a>
            </li>
          {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
        </ul>
      </div>
    </nav>

    <div class="btp container">
      {% block body_block %}

      {% endblock %}
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>

</html>

templates/figures/r_add_form.html
{% extends 'base.html' %}
{% block body_block %}

<h1 class="">
{% if self.object is None %}
  Dodaj pozycję
{% else %}
  Zaktualizuj pozycję
{% endif %}
</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Zapisz">
</form>

{% endblock %}

templates/figures/r_delete.html
{% extends 'base.html' %}
{% block body_block %}

<h1 class="color">Chcesz usunąć {{ object.name }}?</h1>

<form class="" method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Usuń">
  <button type="button" class="btn btn-primary" onclick="location.href='{% url 'figures:tables'%}'" name="button">Anuluj</button>

</form>

{% endblock %}

templates/figures/r_list.html
{% extends 'base.html' %}
{% load has_group %}
{% load static %}
{% block body_block %}

{% if user.is_authenticated %}

<div class="">
  <img src="{% static 'images/salsa.jpg' %}"  class="rounded img-fluid img-thumbnail mx-auto" alt="">
</div>
<div>
<h1 class="pb-2 pt-5">Słowniczek:</h1>

{% if dictionary_table %}
  <table class='table table-hover the-table mx-auto' style="color:white; background-color:#0f486c">
    <thead class="colored">
      <tr class="">
        <th>Nazwa</th>
        <th>Opis</th>
        <th>Link</th>
        {% if request.user|has_group:'admin_group' or user.is_superuser %}
        <th></th>
        {% endif %}
      </tr>
    </thead>
    {% for word in dictionary_table %}
      <tr>
        <td><b>{{ word.name }}</b></td>
        <td>{{ word.description }}</td>
        {% if word.url %}
          <td><a href="{{ word.url }}">Wideo</a></td>
          {% else %}
          <td>N/A</td>
          {%endif%}
          {% if request.user|has_group:'admin_group' or user.is_superuser %}
        <td><button type="button" class="btn btn-danger" onclick="location.href='{% url 'figures:delete_word' pk=word.id %}'">Usuń</button></td>
          {% endif %}
      </tr>
    {% endfor %}
  </table>
{% else %}
  <h3>Brak pozycji w bazie danych.</h3>
{% endif %}

{% if request.user|has_group:'admin_group' or user.is_superuser %}
<div class="">
  <button type="button" class='btn btn-primary' onclick="location.href='{% url 'figures:create_word' %}'">Dodaj pozycję</button>
</div>
{% endif %}
</div>

<div class="py-5">

<h1 class="pb-2">Figury:</h1>

{% if figures_table %}
  <table class='table the-table table-hover'style="color:white; background-color:#0f486c">
    <thead class="colored">
      <tr class="">
        <th>Nazwa</th>
        <th>Opis</th>
        <th>Link</th>
        {% if request.user|has_group:'admin_group' or user.is_superuser %}
          <th></th>
        {% endif %}
      </tr>
    </thead>
    {% for figure in figures_table %}
      <tr>
        <td><b>{{ figure.name }}</b></td>
        <td>{{ figure.description }}</td>
        {% if figure.url %}
          <td><a href="{{ figure.url }}">Wideo</a></td>
          {% else %}
          <td>N/A</td>
          {%endif%}
          {% if request.user|has_group:'admin_group' or user.is_superuser %}
            <td><button type="button" class="btn btn-danger" onclick="location.href='{% url 'figures:delete_figure' pk=figure.id %}'">Usuń</button></td>
          {% endif %}
      </tr>
    {% endfor %}
  </table>
{% else %}
  <h3>Brak pozycji w bazie danych.</h3>
{% endif %}

{% if request.user|has_group:'admin_group' or user.is_superuser %}
<div class="">
  <button type="button" class='btn btn-primary' onclick="location.href='{% url 'figures:create_figure' %}'">Dodaj pozycję</button>
</div>
{% endif %}
</div>

{% else %}
<h1>Zaloguj się aby zobaczyć zawartość</h1>
{% endif %}

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="jumbotron" style="background-color:#FF4500;">
    {% if user.is_authenticated %}
      <h1 class="" >Witaj {{user.username}}!</h1>
      <h4>Aby przejść do zawartości kliknij odpowiedni link na górze strony</h4>
    {% else %}
      <h1 class="py-5" >Witaj na stronie grupy "Salsa pod chmurką"!</h1>
      <h4>Zaloguj się aby zobaczyć zawartość.</h4>
    {% endif %}
  </div>
{% endblock %}